# basic options
title: CCDM Programming Club
author: Darcy Jones
#email: your-email@domain.com
#description: A wonderful site

# Build settings
#markdown: kramdown
theme: minima
show_excerpts: true

disqus:
  shortname: ccdm-programming-club-github-io
